# Site settings
title: "Rachel Metcalf"
email: rmetcalf@live.unc.edu
description: "Personal webpage for Rachel Metcalf."
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "Undergraduate student at the University of North Carolina at Chapel Hill."
title_image: "https://avatars2.githubusercontent.com/u/13002608?v=3&s=460"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/rcmetcalf/rcmetcalf.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: rmetcow
github_username:  rcmetcalf
linkedin_link: https://www.linkedin.com/in/rachelmetcalf


# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
